# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 11:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=256)),
                ('rvcontinue', models.CharField(blank=True, default='0', max_length=32)),
                ('spam_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('language', models.CharField(choices=[('', '-------'), ('en', 'English'), ('de', 'German'), ('eu', 'Basque')], db_index=True, default='', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorDataDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(default='', max_length=85)),
                ('o_adds', models.IntegerField()),
                ('o_adds_surv_48h', models.IntegerField()),
                ('dels', models.IntegerField()),
                ('dels_surv_48h', models.IntegerField()),
                ('reins', models.IntegerField()),
                ('reins_surv_48h', models.IntegerField()),
                ('persistent_o_adds', models.IntegerField()),
                ('persistent_actions', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('editor_id', models.IntegerField()),
                ('year_month', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorDataDeNotIndexed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(default='', max_length=85)),
                ('o_adds', models.IntegerField()),
                ('o_adds_surv_48h', models.IntegerField()),
                ('dels', models.IntegerField()),
                ('dels_surv_48h', models.IntegerField()),
                ('reins', models.IntegerField()),
                ('reins_surv_48h', models.IntegerField()),
                ('persistent_o_adds', models.IntegerField()),
                ('persistent_actions', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('editor_id', models.IntegerField()),
                ('year_month', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorDataEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(default='', max_length=85)),
                ('o_adds', models.IntegerField()),
                ('o_adds_surv_48h', models.IntegerField()),
                ('dels', models.IntegerField()),
                ('dels_surv_48h', models.IntegerField()),
                ('reins', models.IntegerField()),
                ('reins_surv_48h', models.IntegerField()),
                ('persistent_o_adds', models.IntegerField()),
                ('persistent_actions', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('editor_id', models.IntegerField()),
                ('year_month', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorDataEnNotIndexed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(default='', max_length=85)),
                ('o_adds', models.IntegerField()),
                ('o_adds_surv_48h', models.IntegerField()),
                ('dels', models.IntegerField()),
                ('dels_surv_48h', models.IntegerField()),
                ('reins', models.IntegerField()),
                ('reins_surv_48h', models.IntegerField()),
                ('persistent_o_adds', models.IntegerField()),
                ('persistent_actions', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('editor_id', models.IntegerField()),
                ('year_month', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorDataEu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(default='', max_length=85)),
                ('o_adds', models.IntegerField()),
                ('o_adds_surv_48h', models.IntegerField()),
                ('dels', models.IntegerField()),
                ('dels_surv_48h', models.IntegerField()),
                ('reins', models.IntegerField()),
                ('reins_surv_48h', models.IntegerField()),
                ('persistent_o_adds', models.IntegerField()),
                ('persistent_actions', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('editor_id', models.IntegerField()),
                ('year_month', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorDataEuNotIndexed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(default='', max_length=85)),
                ('o_adds', models.IntegerField()),
                ('o_adds_surv_48h', models.IntegerField()),
                ('dels', models.IntegerField()),
                ('dels_surv_48h', models.IntegerField()),
                ('reins', models.IntegerField()),
                ('reins_surv_48h', models.IntegerField()),
                ('persistent_o_adds', models.IntegerField()),
                ('persistent_actions', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('editor_id', models.IntegerField()),
                ('year_month', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
