# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 10:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, help_text='Wikipedia page id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('rvcontinue', models.CharField(blank=True, default='0', max_length=32)),
                ('spam', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('hash_value', models.CharField(default='', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParagraphSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='wikiwho.Paragraph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, help_text='Wikipedia revision id', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('length', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wikiwho.Article')),
                ('editor', models.CharField(max_length=87)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevisionParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wikiwho.Paragraph')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='wikiwho.Revision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('hash_value', models.CharField(default='', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentenceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='wikiwho.Sentence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('last_used', models.PositiveIntegerField(default=0)),
                ('inbound', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('outbound', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('token_id', models.PositiveIntegerField()),
                ('label_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introduced_tokens', to='wikiwho.Revision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sentencetoken',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='wikiwho.Token'),
        ),
        migrations.AddField(
            model_name='paragraphsentence',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='wikiwho.Sentence'),
        ),
    ]
