# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiwho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='article',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='revisions', to='wikiwho.Article', db_column='article'),
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='article',
            new_name='article_id',
        ),
        migrations.AlterField(
            model_name='revision',
            name='article_id',
            field=models.IntegerField(blank=False, null=False),
        ),

        migrations.AlterField(
            model_name='revisionparagraph',
            name='revision',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='paragraphs', to='wikiwho.Revision', db_column='revision'),
        ),
        migrations.RenameField(
            model_name='revisionparagraph',
            old_name='revision',
            new_name='revision_id',
        ),
        migrations.AlterField(
            model_name='revisionparagraph',
            name='revision_id',
            field=models.IntegerField(blank=False, null=False),
        ),

        migrations.AlterField(
            model_name='revisionparagraph',
            name='paragraph',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='revisions', to='wikiwho.Paragraph', db_column='paragraph'),
        ),
        migrations.RenameField(
            model_name='revisionparagraph',
            old_name='paragraph',
            new_name='paragraph_id',
        ),
        migrations.AlterField(
            model_name='revisionparagraph',
            name='paragraph_id',
            field=models.UUIDField(blank=False, null=False, editable=False),
        ),

        migrations.AlterField(
            model_name='paragraphsentence',
            name='paragraph',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='sentences', to='wikiwho.Paragraph', db_column='paragraph'),
        ),
        migrations.RenameField(
            model_name='paragraphsentence',
            old_name='paragraph',
            new_name='paragraph_id',
        ),
        migrations.AlterField(
            model_name='paragraphsentence',
            name='paragraph_id',
            field=models.UUIDField(blank=False, null=False, editable=False),
        ),

        migrations.AlterField(
            model_name='paragraphsentence',
            name='sentence',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='paragraphs', to='wikiwho.Sentence', db_column='sentence'),
        ),
        migrations.RenameField(
            model_name='paragraphsentence',
            old_name='sentence',
            new_name='sentence_id',
        ),
        migrations.AlterField(
            model_name='paragraphsentence',
            name='sentence_id',
            field=models.UUIDField(blank=False, null=False, editable=False),
        ),

        migrations.AlterField(
            model_name='sentencetoken',
            name='sentence',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='tokens', to='wikiwho.Sentence', db_column='sentence'),
        ),
        migrations.RenameField(
            model_name='sentencetoken',
            old_name='sentence',
            new_name='sentence_id',
        ),
        migrations.AlterField(
            model_name='sentencetoken',
            name='sentence_id',
            field=models.UUIDField(blank=False, null=False, editable=False),
        ),

        migrations.AlterField(
            model_name='sentencetoken',
            name='token',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='sentences', to='wikiwho.Token', db_column='token'),
        ),
        migrations.RenameField(
            model_name='sentencetoken',
            old_name='token',
            new_name='token_id',
        ),
        migrations.AlterField(
            model_name='sentencetoken',
            name='token_id',
            field=models.UUIDField(blank=False, null=False, editable=False),
        ),

        migrations.AlterField(
            model_name='token',
            name='label_revision',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='introduced_tokens', to='wikiwho.Revision', db_column='label_revision'),
        ),
        migrations.RenameField(
            model_name='token',
            old_name='label_revision',
            new_name='label_revision_id',
        ),
        migrations.AlterField(
            model_name='token',
            name='label_revision_id',
            field=models.IntegerField(blank=False, null=False),
        ),
    ]
