# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiwho', '0003_auto_20171005_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorDataEs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(default='', max_length=85)),
                ('o_adds', models.IntegerField()),
                ('o_adds_surv_48h', models.IntegerField()),
                ('dels', models.IntegerField()),
                ('dels_surv_48h', models.IntegerField()),
                ('reins', models.IntegerField()),
                ('reins_surv_48h', models.IntegerField()),
                ('persistent_o_adds', models.IntegerField()),
                ('persistent_actions', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('editor_id', models.IntegerField()),
                ('year_month', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorDataEsNotIndexed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(default='', max_length=85)),
                ('o_adds', models.IntegerField()),
                ('o_adds_surv_48h', models.IntegerField()),
                ('dels', models.IntegerField()),
                ('dels_surv_48h', models.IntegerField()),
                ('reins', models.IntegerField()),
                ('reins_surv_48h', models.IntegerField()),
                ('persistent_o_adds', models.IntegerField()),
                ('persistent_actions', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('editor_id', models.IntegerField()),
                ('year_month', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorDataTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(default='', max_length=85)),
                ('o_adds', models.IntegerField()),
                ('o_adds_surv_48h', models.IntegerField()),
                ('dels', models.IntegerField()),
                ('dels_surv_48h', models.IntegerField()),
                ('reins', models.IntegerField()),
                ('reins_surv_48h', models.IntegerField()),
                ('persistent_o_adds', models.IntegerField()),
                ('persistent_actions', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('editor_id', models.IntegerField()),
                ('year_month', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorDataTrNotIndexed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(default='', max_length=85)),
                ('o_adds', models.IntegerField()),
                ('o_adds_surv_48h', models.IntegerField()),
                ('dels', models.IntegerField()),
                ('dels_surv_48h', models.IntegerField()),
                ('reins', models.IntegerField()),
                ('reins_surv_48h', models.IntegerField()),
                ('persistent_o_adds', models.IntegerField()),
                ('persistent_actions', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('editor_id', models.IntegerField()),
                ('year_month', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('', '-------'), ('en', 'English'), ('de', 'German'), ('eu', 'Basque'), ('tr', 'Turkish'), ('es', 'Spanish')], db_index=True, default='', max_length=2),
        ),
    ]
