# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiwho', '0008_indexes_positions'),
    ]

    operations = [
        migrations.RunSQL(
            # CREATE INDEX orders_unbilled_index ON orders(order_nr) WHERE billed is not true;
            sql='CREATE INDEX wikiwho_is_article_id ON public.wikiwho_article (id) WHERE is_article is true;',
            reverse_sql='DROP INDEX public.wikiwho_is_article_id;'
        ),

        # we need this indexes for deleted_content queries
        migrations.RunSQL(
            sql='CREATE INDEX wikiwho_token_label_revision_id ON public.wikiwho_token USING btree (label_revision_id);',
            reverse_sql='DROP INDEX public.wikiwho_token_label_revision_id'
        ),
        # migrations.RunSQL(
        #     sql='CREATE INDEX wikiwho_token_token_id ON public.wikiwho_token USING btree (token_id);',
        #     reverse_sql='DROP INDEX public.wikiwho_token_token_id;'
        # ),
        migrations.RunSQL(
            sql='CREATE INDEX wikiwho_token_last_used ON public.wikiwho_token USING btree (last_used);',
            reverse_sql='DROP INDEX public.wikiwho_token_last_used;'
        ),
        # TODO should we do this only for len comparision?
        # migrations.RunSQL(
        #     sql='CREATE INDEX wikiwho_token_label_outbound ON public.wikiwho_token USING gin (outbound);',
        #     reverse_sql='DROP INDEX public.wikiwho_token_label_outbound;'
        # )
    ]

    # HACK: always fake. These fields are actually not FK on db.
    # This is done to use django's fk queries, emulated cascaded deletion
    def apply(self, project_state, schema_editor, collect_sql=False):
        return project_state.clone()
        # return project_state

    def unapply(self, project_state, schema_editor, collect_sql=False):
        return project_state.clone()
        # return project_state
