# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiwho', '0009_indexes_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='conflict_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='editor',
            field=models.CharField(default='', help_text='Editor of label revision', max_length=87),
        ),
        migrations.AddField(
            model_name='token',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp of label revision', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='article_id',
            field=models.IntegerField(blank=False, null=False),
        ),
    ]
