# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiwho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='article',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='revisions', to='wikiwho.Article', db_column='article'),
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='article',
            new_name='article_id',
        ),
        migrations.AlterField(
            model_name='revision',
            name='article_id',
            field=models.IntegerField(blank=False, null=False),
        ),

        migrations.AlterField(
            model_name='revisionparagraph',
            name='revision',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='paragraphs', to='wikiwho.Revision', db_column='revision'),
        ),
        migrations.RenameField(
            model_name='revisionparagraph',
            old_name='revision',
            new_name='revision_id',
        ),
        migrations.AlterField(
            model_name='revisionparagraph',
            name='revision_id',
            field=models.IntegerField(blank=False, null=False),
        ),

        migrations.AlterField(
            model_name='revisionparagraph',
            name='paragraph',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='revisions', to='wikiwho.Paragraph', db_column='paragraph'),
        ),
        migrations.RenameField(
            model_name='revisionparagraph',
            old_name='paragraph',
            new_name='paragraph_id',
        ),
        migrations.AlterField(
            model_name='revisionparagraph',
            name='paragraph_id',
            field=models.UUIDField(blank=False, null=False, editable=False),
        ),

        migrations.AlterField(
            model_name='paragraphsentence',
            name='paragraph',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='sentences', to='wikiwho.Paragraph', db_column='paragraph'),
        ),
        migrations.RenameField(
            model_name='paragraphsentence',
            old_name='paragraph',
            new_name='paragraph_id',
        ),
        migrations.AlterField(
            model_name='paragraphsentence',
            name='paragraph_id',
            field=models.UUIDField(blank=False, null=False, editable=False),
        ),

        migrations.AlterField(
            model_name='paragraphsentence',
            name='sentence',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='paragraphs', to='wikiwho.Sentence', db_column='sentence'),
        ),
        migrations.RenameField(
            model_name='paragraphsentence',
            old_name='sentence',
            new_name='sentence_id',
        ),
        migrations.AlterField(
            model_name='paragraphsentence',
            name='sentence_id',
            field=models.UUIDField(blank=False, null=False, editable=False),
        ),

        migrations.AlterField(
            model_name='sentencetoken',
            name='sentence',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='tokens', to='wikiwho.Sentence', db_column='sentence'),
        ),
        migrations.RenameField(
            model_name='sentencetoken',
            old_name='sentence',
            new_name='sentence_id',
        ),
        migrations.AlterField(
            model_name='sentencetoken',
            name='sentence_id',
            field=models.UUIDField(blank=False, null=False, editable=False),
        ),

        migrations.AlterField(
            model_name='sentencetoken',
            name='token',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='sentences', to='wikiwho.Token', db_column='token'),
        ),
        migrations.RenameField(
            model_name='sentencetoken',
            old_name='token',
            new_name='token_id',
        ),
        migrations.AlterField(
            model_name='sentencetoken',
            name='token_id',
            field=models.UUIDField(blank=False, null=False, editable=False),
        ),

        migrations.AlterField(
            model_name='token',
            name='label_revision',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='introduced_tokens', to='wikiwho.Revision', db_column='label_revision'),
        ),
        migrations.RenameField(
            model_name='token',
            old_name='label_revision',
            new_name='label_revision_id',
        ),
        migrations.AlterField(
            model_name='token',
            name='label_revision_id',
            field=models.IntegerField(blank=False, null=False),
        ),

        # https://docs.djangoproject.com/en/1.10/ref/migration-operations/#django.db.migrations.operations.RunSQL
        # migrations.RunSQL(
        #     sql='ALTER TABLE public.wikiwho_token DROP CONSTRAINT wikiwho_token_pkey;',
        #     reverse_sql='ALTER TABLE public.wikiwho_token ADD CONSTRAINT wikiwho_token_pkey PRIMARY KEY(id);'
        # ),
        #
        # migrations.RunSQL(
        #     sql='ALTER TABLE public.wikiwho_sentence DROP CONSTRAINT wikiwho_sentence_pkey;',
        #     reverse_sql='ALTER TABLE public.wikiwho_sentence ADD CONSTRAINT wikiwho_sentence_pkey PRIMARY KEY(id);'
        # ),
        #
        # migrations.RunSQL(
        #     sql='ALTER TABLE public.wikiwho_paragraph DROP CONSTRAINT wikiwho_paragraph_pkey;',
        #     reverse_sql='ALTER TABLE public.wikiwho_paragraph ADD CONSTRAINT wikiwho_paragraph_pkey PRIMARY KEY(id);'
        # ),
        #
        # migrations.RunSQL(
        #     sql='ALTER TABLE public.wikiwho_revision DROP CONSTRAINT wikiwho_revision_pkey;',
        #     reverse_sql='ALTER TABLE public.wikiwho_revision ADD CONSTRAINT wikiwho_revision_pkey PRIMARY KEY(id);'
        # ),
        #
        # migrations.RunSQL(
        #     sql='ALTER TABLE public.wikiwho_article DROP CONSTRAINT wikiwho_article_pkey;',
        #     reverse_sql='ALTER TABLE public.wikiwho_article ADD CONSTRAINT wikiwho_article_pkey PRIMARY KEY(id);'
        # ),

        # migrations.RunSQL(
        #     sql='ALTER TABLE public.wikiwho_revisionparagraph DROP CONSTRAINT wikiwho_revisionparagraph_pkey;',
        #     reverse_sql='ALTER TABLE public.wikiwho_revisionparagraph ADD CONSTRAINT wikiwho_revisionparagraph_pkey PRIMARY KEY(id);'
        # ),
        #
        # migrations.RunSQL(
        #     sql='ALTER TABLE public.wikiwho_paragraphsentence DROP CONSTRAINT wikiwho_paragraphsentence_pkey;',
        #     reverse_sql='ALTER TABLE public.wikiwho_paragraphsentence ADD CONSTRAINT wikiwho_paragraphsentence_pkey PRIMARY KEY(id);'
        # ),
        #
        # migrations.RunSQL(
        #     sql='ALTER TABLE public.wikiwho_sentencetoken DROP CONSTRAINT wikiwho_sentencetoken_pkey;',
        #     reverse_sql='ALTER TABLE public.wikiwho_sentencetoken ADD CONSTRAINT wikiwho_sentencetoken_pkey PRIMARY KEY(id);'
        # )
    ]