# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_editor', '0002_auto_20190509_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editordatade',
            old_name='undos',
            new_name='conflicts',
        ),
        migrations.RenameField(
            model_name='editordatadenotindexed',
            old_name='undos',
            new_name='conflicts',
        ),
        migrations.RenameField(
            model_name='editordataen',
            old_name='undos',
            new_name='conflicts',
        ),
        migrations.RenameField(
            model_name='editordataennotindexed',
            old_name='undos',
            new_name='conflicts',
        ),
        migrations.RenameField(
            model_name='editordataes',
            old_name='undos',
            new_name='conflicts',
        ),
        migrations.RenameField(
            model_name='editordataesnotindexed',
            old_name='undos',
            new_name='conflicts',
        ),
        migrations.RenameField(
            model_name='editordataeu',
            old_name='undos',
            new_name='conflicts',
        ),
        migrations.RenameField(
            model_name='editordataeunotindexed',
            old_name='undos',
            new_name='conflicts',
        ),
        migrations.RenameField(
            model_name='editordatatr',
            old_name='undos',
            new_name='conflicts',
        ),
        migrations.RenameField(
            model_name='editordatatrnotindexed',
            old_name='undos',
            new_name='conflicts',
        ),
    ]
