# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='longfailedarticle',
            name='language',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='recursionerrorarticle',
            name='language',
            field=models.CharField(default='', max_length=32),
        ),
    ]
