# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170915_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longfailedarticle',
            name='language',
            field=models.CharField(choices=[('', '-------'), ('en', 'English'), ('de', 'German'), ('eu', 'Basque'), ('tr', 'Turkish')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='recursionerrorarticle',
            name='language',
            field=models.CharField(choices=[('', '-------'), ('en', 'English'), ('de', 'German'), ('eu', 'Basque'), ('tr', 'Turkish')], default='', max_length=8),
        ),
    ]
