# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171005_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longfailedarticle',
            old_name='id',
            new_name='page_id',
        ),
        migrations.AlterField(
            model_name='longfailedarticle',
            name='page_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddField(
            model_name='longfailedarticle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameField(
            model_name='recursionerrorarticle',
            old_name='id',
            new_name='page_id',
        ),
        migrations.AlterField(
            model_name='recursionerrorarticle',
            name='page_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddField(
            model_name='recursionerrorarticle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
