# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180105_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longfailedarticle',
            name='language',
            field=models.CharField(choices=[('', '-------'), ('en', 'English'), ('de', 'German'), ('eu', 'Basque'), ('tr', 'Turkish'), ('es', 'Spanish'), ('fr', 'French')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='recursionerrorarticle',
            name='language',
            field=models.CharField(choices=[('', '-------'), ('en', 'English'), ('de', 'German'), ('eu', 'Basque'), ('tr', 'Turkish'), ('es', 'Spanish'), ('fr', 'French')], default='', max_length=8),
        ),
    ]
