# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0003_add_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apirequestlog',
            name='data',
        ),
        migrations.RemoveField(
            model_name='apirequestlog',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='apirequestlog',
            name='method',
        ),
        migrations.RemoveField(
            model_name='apirequestlog',
            name='response',
        ),
        migrations.RemoveField(
            model_name='apirequestlog',
            name='view',
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='page_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Article id', null=True),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='query_params',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
