# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0005_auto_20170317_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apirequestlog',
            name='host',
        ),
        migrations.RemoveField(
            model_name='apirequestlog',
            name='remote_addr',
        ),
        migrations.RemoveField(
            model_name='apirequestlog',
            name='user',
        ),
    ]
