# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0006_auto_20170331_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='remote_addr',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
