# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0008_remove_apirequestlog_remote_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='language',
            field=models.CharField(choices=[('', '-------'), ('en', 'English'), ('de', 'German'), ('eu', 'Basque')], default='', max_length=8),
        ),
    ]
