# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0012_auto_20180105_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequestlog',
            old_name='page_id',
            new_name='instance_id',
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='type_id',
            field=models.CharField(blank=True, db_index=True, default='page_id', 
                help_text='most relevant instance', max_length=15, null=True),
        ),
    ]
