# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0016_auto_20230426_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='language',
            field=models.CharField(choices=[('', '-------'), ('en', 'English'), ('de', 'German'), ('eu', 'Basque'), ('tr', 'Turkish'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('hu', 'Hungarian')], default='', max_length=8),
        ),
    ]
